### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by fanxiao2-zzu-fan** [furkan-luleci/Labeled-acceleration-data-augmentation-for-structural-damage-detection#1]
Hello, may I ask about the format of the dataset? Can you provide a dataset instance?

**Comment by furkan-luleci** [comment]
I just shared an example vibration dataset and its description. Please also take a look at the publication as I explained the dataset used in the study in much more detail:
https://link.springer.com/article/10.1007/s13349-022-00627-8
Let me know if you have further questions...
